@hostname = http://localhost:3000/api/v1
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWRlMDIyODk5Zjg4MzIzYmQ1MjZlZDUiLCJmaXJzdE5hbWUiOiJBbmRyZXMiLCJsYXN0TmFtZSI6IkZlbGlwZURNIiwiZW1haWwiOiJmZWxpcGUuZGlhZ29AdGhlYml0YmFuZy5jb21wYW55Iiwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MTI3NTY5MzQsImV4cCI6MTcxMjc2MDUzNH0.LYy17hUdKTHZpa8rGazdrnU_bxte16a9znL-AdbtvUY
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWRlMDIyODk5Zjg4MzIzYmQ1MjZlZDUiLCJmaXJzdE5hbWUiOiJBbmRyZXMiLCJsYXN0TmFtZSI6IkZlbGlwZURNIiwiZW1haWwiOiJmZWxpcGUuZGlhZ29AdGhlYml0YmFuZy5jb21wYW55Iiwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MTA4NjExODAsImV4cCI6MTcxMTQ2NTk4MH0.tgrf12TKxOZVWQk6z7vj0zzJyuABIjyc7uBdEo1TLBE

### GET app /
GET http://localhost:3000/

### GET home
GET http://localhost:3000/home

### GET about
GET http://localhost:3000/about
